KingdomFirst/RockAssemblies

- rocks.kfs.Workflow.Action.Prayer/AddPrayerRequest.cs
* Added option for single select field type in case needed a custom category list.
* Added option to store the guid of the newly created prayer request in the workflow.
---------
New Hope Church
---------
_Prayer Request Setting_
---------
* `rocks.kfs.Workflow.Action.Prayer/AddPrayerRequest.cs`
---------
No
> Workflow Prayer Request Action Enhancements

- rocks.kfs.WorkflowFromEWS/Jobs/StartWorkflow.cs
- rocks.kfs.WorkflowFromEWS/Properties/AssemblyInfo.cs
- rocks.kfs.WorkflowFromEWS/packages.config
- rocks.kfs.WorkflowFromEWS/rocks.kfs.WorkflowFromEWS.csproj
This job uses the Exchange Web Services to connect to an Exchange Server or Office 365 and kicks off a selected Workflow Type.  It can be configured to initiate a Workflow for every message or it can group by Conversation Id and only create one Workflow, appending the body of subsequent messages to an existing Workflow.
---------
KFS
---------
---------
* `rocks.kfs.WorkflowFromEWS/Jobs/StartWorkflow.cs`
* `rocks.kfs.WorkflowFromEWS/Properties/AssemblyInfo.cs`
* `rocks.kfs.WorkflowFromEWS/packages.config`
* `rocks.kfs.WorkflowFromEWS/rocks.kfs.WorkflowFromEWS.csproj`
---------
No
> Added job that creates workflows from Exchange

- rocks.kfs.Intacct/IntacctJournal.cs
- rocks.kfs.Intacct/IntacctModels.cs
Added ability to pass in lava to intacct export features to get a customized memo field in intacct export. Fixes #3 
- New settings added on https://github.com/KingdomFirst/RockBlocks/pull/7
---------
- Added ability to pass in lava to intacct export to get a customized memo field.
---------
OHC
---------
See https://github.com/KingdomFirst/RockBlocks/pull/7
---------
- rocks.kfs.Intacct/IntacctJournal.cs
- rocks.kfs.Intacct/IntacctModels.cs
---------
Yes, block and assembly must be updated at the same time otherwise you will get mismatched function calls. https://github.com/KingdomFirst/RockBlocks/pull/7
> Intacct Memo field Lava Support

- rocks.kfs.FundraisingParticipantSummary/Jobs/FundraisingParticipantSummary.cs
Add new "ContributionTotal" lava field instead of having to subtract it in the lava again.
---------
Add new `ContributionTotal` lava field instead of having to subtract it in the lava again.
---------
Kensington
---------
No
---------
rocks.kfs.FundraisingParticipantSummary/Jobs/FundraisingParticipantSummary.cs
---------
No
> Fundraising Participant Job Minor Tweak

- rocks.kfs.Reach/Gateway.cs
- rocks.kfs.Reach/Properties/AssemblyInfo.cs
- rocks.kfs.Reach/Reporting/Api.cs
+ Added a new setting to disable "Update Primary Email" when matching a person record.
`Update Primary Email`
---------
- Added a new setting to disable "Update Primary Email" when matching a person record.
---------
Kensington
---------
---------
- rocks.kfs.Reach/Gateway.cs
- rocks.kfs.Reach/Properties/AssemblyInfo.cs
- rocks.kfs.Reach/Reporting/Api.cs
---------
No
> Reach Update Primary Email Address Setting

- rocks.kfs.WorkflowFromEWS/Jobs/StartWorkflow.cs
Fix for IsActive workflow, not an actual database member, changed to check the fields the method does. Changed Sort order to OrderBy Date *Descending* due to using it in a group with no deleted emails.
---------
- Fixed checking for existing active workflows that generated an exception.
- Changed Sort order to OrderBy Date *Descending* due to using it in a group with no deleted emails.
---------
Warranty
---------
No
---------
rocks.kfs.WorkflowFromEWS/Jobs/StartWorkflow.cs
---------
No
> Rock Job EWS to Workflow Bug Fix

- rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupEmail.cs
- rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupSMS.cs
- rocks.kfs.ScheduledGroupCommunication/Migrations/001_AddSystemData.cs
+ Added a possible fix for duplicate scheduled group communications. (Fixes https://github.com/KingdomFirst/RockBlocks/issues/21)
- **Last Run Buffer**: Use this setting to add a buffer to not double send, too large of a buffer may cause messages to be missed. By default this job will send any communications that have been scheduled since the last run date time minus the LastRunDurationSeconds, due to the way some server schedules run it is possible to be a few seconds off and double send.
---------
+ Added a possible fix for duplicate scheduled group communications.
---------
Warranty/Biltmore
---------
---------
rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupEmail.cs
rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupSMS.cs …
> Scheduled Group Communication Fix

- rocks.kfs.EventBrite/Eventbrite.cs
Eventbrite Null reference exception fix from awhile ago that I forgot :( 
---------
Fixed a potential issue when an attendee PersonAlias is null.
---------
Warranty
---------
No
---------
rocks.kfs.EventBrite/Eventbrite.cs
---------
No
> Eventbrite Null reference exception fix

- rocks.kfs.EventBrite/Eventbrite.cs
- rocks.kfs.EventBrite/Properties/AssemblyInfo.cs
Got a null reference exception when I ran Eventbrite sync locally, decided to fix it so I could test another potential issue. 
---------
- Fixed a potential null reference exception when Rock would not return a primary family. 
---------
Warranty
---------
No
---------
rocks.kfs.EventBrite/Eventbrite.cs
---------
No
> Eventbrite Null Reference Fix

- rocks.kfs.EventBrite/Entities/RockEventbriteEvent.cs
- rocks.kfs.EventBrite/Eventbrite.cs
- rocks.kfs.EventBrite/Field/Types/EventbriteEventFieldType.cs
- rocks.kfs.EventBrite/Properties/AssemblyInfo.cs
Organization that was stored in settings was not being taken into account properly.
---------
* Fixed issue where Organization may not be taken into account when running any Eventbrite sync methods.
---------
Support
---------
No
---------
- rocks.kfs.EventBrite/Entities/RockEventbriteEvent.cs
- rocks.kfs.EventBrite/Eventbrite.cs
- rocks.kfs.EventBrite/Field/Types/EventbriteEventFieldType.cs
---------
No, existing methods should still work.
> Eventbrite Organization Fix

- rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupEmail.cs
- rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupSMS.cs
- rocks.kfs.ScheduledGroupCommunication/Migrations/002_AddRecurrenceAttribute.cs
- rocks.kfs.ScheduledGroupCommunication/Properties/AssemblyInfo.cs
- rocks.kfs.ScheduledGroupCommunication/SystemGuid/Attribute.cs
- rocks.kfs.ScheduledGroupCommunication/rocks.kfs.ScheduledGroupCommunication.csproj
* Added "Recurrence" single select attribute to Scheduled Emails and Scheduled SMS Messages attribute matrix templates. The single select attribute has values of OneTime, Weekly, BiWeekly, and Monthly.  
* Added logic to KFS SendScheduledGroupEmail and SendScheduledGroupSMS jobs to handle recurrence. 
---------
* Added "Recurrence" single select attribute to Scheduled Emails and Scheduled SMS Messages attribute matrix templates. The single select attribute has values of OneTime, Weekly, BiWeekly, and Monthly.  
* Added logic to KFS SendScheduledGroupEmail and SendScheduledGroupSMS jobs to handle recurrence.   
---------
First Presbyterian Church of Greenville, SC
---------
New Recurrence attribute in Group Type edit screen:  
Email Matrix Attribute
SMS Matrix Attribute
---------
* …
> F: gm-scheduledGroupComm

- rocks.kfs.Security.ExternalAuthentication.DoorkeeperOAuth/DoorkeeperOAuth.cs
Fixes the country integration for DoorKeeper authentication calls
None.
---------
* Fixed the country integration from DoorKeeper oAuth
---------
KFS Warranty
---------
N/A
---------
* rocks.kfs.Security.ExternalAuthentication.DoorkeeperOAuth/DoorkeeperOAuth.cs - adjust country processing
---------
None
> Add country to location service call and gather it from the oauth call.

- rocks.kfs.Intacct/Enums/PaymentMethod.cs
- rocks.kfs.Intacct/IntacctCheckingAccountList.cs
- rocks.kfs.Intacct/IntacctEndpoint.cs
- rocks.kfs.Intacct/IntacctJournal.cs
- rocks.kfs.Intacct/IntacctModels.cs
- rocks.kfs.Intacct/IntacctOtherReceipt.cs
- rocks.kfs.Intacct/Properties/AssemblyInfo.cs
- rocks.kfs.Intacct/Utils/TransactionHelpers.cs
- rocks.kfs.Intacct/rocks.kfs.Intacct.csproj
Enhanced KFS's Intacct api interface to support creation of Other Receipts in Intacct account.
---------
* Enhanced KFS's Intacct api interface to support creation of Other Receipts in Intacct account.
---------
River Point Church
---------
See RockBlocks PR for details.
---------
* rocks.kfs.Intacct/Enums/PaymentMethod.cs
* rocks.kfs.Intacct/IntacctCheckingAccountList.cs
* rocks.kfs.Intacct/IntacctEndpoint.cs
* rocks.kfs.Intacct/IntacctModels.cs
* rocks.kfs.Intacct/IntacctOtherReceipt.cs
* rocks.kfs.Intacct/rocks.kfs.Intacct.csproj
---------
none
> Add support for Other Receipts to Intacct api model

- rocks.kfs.Workflow.Action.CheckIn/CheckForEmptyCheckin.cs
- rocks.kfs.Workflow.Action.CheckIn/Properties/AssemblyInfo.cs
- rocks.kfs.Workflow.Action.CheckIn/rocks.kfs.Workflow.Action.CheckIn.csproj
- Created CheckForEmptyCheckin workflow action, that will attach messages to the check-in state to be read by a block during check-in.
- _Error Message Template_, This will be the error message that gets attached to the check-in state for this instance of the action. Logic can be applied based on 'RemovedPeople', 'RemovedGroupTypes', 'RemovedGroups' and 'RemovedLocations'. If you return an empty message it will not display for this instance in our block.
- _Always Log Lava_, Enable this if you want the message to be created no matter the result. By default it will only create a message if all people will be removed, such as when your whole family is already checked in or the classrooms are full.
---------
- Added new Workflow action "Check for Empty Check-in"
--------- …
> New Check-in Workflow Action

- rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedNotifications.cs
- rocks.kfs.StepsToCare/Migrations/003_CreateCommunications.cs
- rocks.kfs.StepsToCare/Migrations/006_AddWorkersOnlyColumn.cs
- rocks.kfs.StepsToCare/Migrations/007_CreateAttribute.cs
- rocks.kfs.StepsToCare/Migrations/008_LavaShortcode.cs
- rocks.kfs.StepsToCare/Migrations/009_CreatePermissions.cs
- rocks.kfs.StepsToCare/Model/CareNeed.cs
- rocks.kfs.StepsToCare/Properties/AssemblyInfo.cs
- rocks.kfs.StepsToCare/SystemGuid/PersonAttribute.cs
- rocks.kfs.StepsToCare/rocks.kfs.StepsToCare.csproj
- Add the new Workers Only column to the data model and table. 
- Add a new person attribute for notification preferences. 
- Update the communication migration to include the proper URL's and SMS values. 
- Update the Job for the new notification preferences and sending SMS.
- Added a Lava shortcode via migration for note template/quick notes capability.
- Added migration for new security permissions added in https://github.com/KingdomFirst/RockBlocks/pull/85
---------
- Add the new Workers Only column to the data model and table. 
- Add a new person attribute for notification preferences. 
- Update the communication migration to include the proper URL's and SMS values. 
- Update the Job for the new notification preferences and sending SMS.
---------
Rock Springs
---------
No
---------
- …
> Steps to Care - Notification Preferences and Workers Only

- KFSRock.sln.kfs
- rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupEmail.cs
- rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupSMS.cs
- rocks.kfs.ScheduledGroupCommunication/Migrations/003_AddDailyRecurrence.cs
- rocks.kfs.ScheduledGroupCommunication/Properties/AssemblyInfo.cs
- rocks.kfs.ScheduledGroupCommunication/ReadMe.md
- rocks.kfs.ScheduledGroupCommunication/rocks.kfs.ScheduledGroupCommunication.csproj
Add option for daily scheduled group communications in both the email and text variety.
* Added Daily option to scheduled group emails
* Added Daily option to scheduled group texts
---------
* Added option for daily recurrence to scheduled group communications
---------
Venture
---------
---------
* rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupEmail.cs - Added processing for daily emails
* rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupSMS.cs - Added processing for daily texts
* rocks.kfs.ScheduledGroupCommunication/Migrations/003_AddDailyRecurrence.cs - Migration to create Daily option
* rocks.kfs.ScheduledGroupCommunication/rocks.kfs.ScheduledGroupCommunication.csproj - Added migration to project file
---------
No, only new options added
> Scheduled Group Communication: Daily Recurrence Option

- rocks.kfs.Shortcodes/EWS/CalendarItems.cs
- rocks.kfs.Shortcodes/Migrations/001_CreateAttribute.cs
- rocks.kfs.Shortcodes/rocks.kfs.Shortcodes.csproj
Once I went to use the EWS Shortcode there were a few minor changes needed.
- Gave the shortcode a new "Name" to prepend KFS to it. 
- Added a note to the "Start" time field that the time is based off of the authenticated user's time zone.
- Added exception log capability as I tried running it and couldn't figure out why it failed until I saw the error.
- Added Attribute Qualifier to the password field so the value doesn't display in global attributes .
---------
- Gave the shortcode a new "Name" to prepend KFS to it. 
- Added a note to the "Start" time field that the time is based off of the authenticated user's time zone.
- Added exception log capability as I tried running it and couldn't figure out why it failed until I saw the error.
- Added Attribute Qualifier to the password field …
> EWS Shortcode Modifications

- rocks.kfs.StepsToCare/Migrations/001_CreateDb.cs
- rocks.kfs.StepsToCare/Migrations/004_CreatePages.cs
- rocks.kfs.StepsToCare/Migrations/010_AddParentNeedId.cs
- rocks.kfs.StepsToCare/Migrations/011_AddWorkerColumns.cs
- rocks.kfs.StepsToCare/Migrations/012_NewBlockSettings.cs
- rocks.kfs.StepsToCare/Model/CareNeed.cs
- rocks.kfs.StepsToCare/Model/CareWorker.cs
- rocks.kfs.StepsToCare/Properties/AssemblyInfo.cs
- rocks.kfs.StepsToCare/rocks.kfs.StepsToCare.csproj
- Added new columns to data model to support sub/family/parent needs. (ParentNeed/ParentNeedId/ChildNeeds)
- Added new criteria to workers for family needs. (Age Range and Gender)
- Fix a cascade permission on care workers and assigned person tables.
See [RockBlocks#95](https://github.com/KingdomFirst/RockBlocks/pull/95) for more information
---------
See [RockBlocks#95](https://github.com/KingdomFirst/RockBlocks/pull/95) for more information
---------
RSC
---------
Not the assembly.
---------
- rocks.kfs.StepsToCare/Migrations/001_CreateDb.cs
- rocks.kfs.StepsToCare/Migrations/004_CreatePages.cs
- rocks.kfs.StepsToCare/Migrations/010_AddParentNeedId.cs
- rocks.kfs.StepsToCare/Migrations/011_AddWorkerColumns.cs
- rocks.kfs.StepsToCare/Migrations/012_NewBlockSettings.cs
- …
> Steps to Care Sub/Family Needs

- rocks.kfs.StepsToCare/Migrations/010_AddParentNeedId.cs
Fix an issue with the migration. Triggers have to happen by themselves.
---------
No
---------
RSC
---------
No
---------
rocks.kfs.StepsToCare/Migrations/010_AddParentNeedId.cs
---------
No
> Steps to Care Migration Issue

- rocks.kfs.StepsToCare/Migrations/012_NewBlockSettings.cs
Add new setting to Migration for Dashboard for Complete Child Needs on Parent Completion. For these block changes: https://github.com/KingdomFirst/RockBlocks/pull/98 
- _Complete Child Needs on Parent Completion_
---------
Add new setting to Dashboard for Complete Child Needs on Parent Completion
---------
RSC
---------
---------
rocks.kfs.StepsToCare/Migrations/012_NewBlockSettings.cs
---------
No
> Steps to Care Sub Needs New Setting

- rocks.kfs.StepsToCare/Migrations/013_NewPermissions.cs
- rocks.kfs.StepsToCare/Migrations/014_NewPageAndAttributes.cs
- rocks.kfs.StepsToCare/rocks.kfs.StepsToCare.csproj
- Add new "Care Needs" page to Person Detail/Profile pages in Rock.
- Added new "CompleteNeeds" and "UpdateStatus" security permissions.
---------
- Add new "Care Needs" page to Person Detail/Profile pages in Rock.
- Added new "CompleteNeeds" and "UpdateStatus" security permissions.
---------
RSC
---------
Adds a new page to person detail section:   
---------
- rocks.kfs.StepsToCare/Migrations/013_NewPermissions.cs
- rocks.kfs.StepsToCare/Migrations/014_NewPageAndAttributes.cs
- rocks.kfs.StepsToCare/rocks.kfs.StepsToCare.csproj
---------
No, though technically it probably would not work with https://github.com/KingdomFirst/RockBlocks/pull/103
> Steps to Care New Migrations for permissions and new page

- rocks.kfs.Checkin.PagerEntry/Migrations/001_PagerEntryInstall.cs
- rocks.kfs.Checkin.PagerEntry/Properties/AssemblyInfo.cs
- rocks.kfs.Checkin.PagerEntry/rocks.kfs.Checkin.PagerEntry.csproj
- Migration for the new block in https://github.com/KingdomFirst/RockBlocks/pull/107
- Adds a new "Pager Number" group type attribute to the Family Group Type.
- Adds blocks to Check-in manager person profile pages to display this new family group type with date last modified.
---------
- Add the ability to have a "Pager Entry" page as part of the check-in process. 
---------
RSC
---------
---------
- rocks.kfs.Checkin.PagerEntry/Migrations/001_PagerEntryInstall.cs
- rocks.kfs.Checkin.PagerEntry/Properties/AssemblyInfo.cs
- rocks.kfs.Checkin.PagerEntry/rocks.kfs.Checkin.PagerEntry.csproj
---------
No
> Pager Entry Migration

- rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedNotifications.cs
- rocks.kfs.StepsToCare/Properties/AssemblyInfo.cs
Make it so the attention needed automated notification only goes to follow up workers instead of all assigned persons.
---------
Make it so the attention needed automated notification only goes to follow up workers instead of all assigned persons.
---------
RSC
---------
No
---------
rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedNotifications.cs
---------
no
> Steps to Care Automated Notification Update

- rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedNotifications.cs
- rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs
- rocks.kfs.StepsToCare/Migrations/015_UpdateJob.cs
- rocks.kfs.StepsToCare/Model/WorkerResult.cs
- rocks.kfs.StepsToCare/Properties/AssemblyInfo.cs
- rocks.kfs.StepsToCare/Utilities.cs
- rocks.kfs.StepsToCare/rocks.kfs.StepsToCare.csproj
Added new utility methods  to make assignments on scheduled future needs. Updated the Care Need automated notifications job to include Future Need assignment.
---------
- Added new capability to system job to assign Care Needs that were scheduled for the future.
---------
RSC
---------
See above.
---------
- rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedNotifications.cs
- rocks.kfs.StepsToCare/Model/WorkerResult.cs
- rocks.kfs.StepsToCare/Properties/AssemblyInfo.cs
- rocks.kfs.StepsToCare/Utilities.cs
- rocks.kfs.StepsToCare/rocks.kfs.StepsToCare.csproj
---------
Yes, the new utility methods are required for block changes in [RockBlocks#114](https://github.com/KingdomFirst/RockBlocks/pull/114)
> Steps to Care Future Needs

- rocks.kfs.Zoom/Migrations/008_MakeCommunicationsEditable.cs
- rocks.kfs.Zoom/Properties/AssemblyInfo.cs
- rocks.kfs.Zoom/rocks.kfs.Zoom.csproj
Fixes ability to edit zoom system communications
---------
* Fixed bug that prevented users from editing the zoom meeting reminder communication
---------
KFS
---------
N/A
---------
* rocks.kfs.Zoom/Migrations/008_MakeCommunicationsEditable.cs - new migration
* rocks.kfs.Zoom/Properties/AssemblyInfo.cs - update version
* rocks.kfs.Zoom/rocks.kfs.Zoom.csproj - added migration to the project
---------
None
> Zoom Reminders Editable

- rocks.kfs.Avalanche/rocks.kfs.Avalanche.csproj
- rocks.kfs.CustomGroupCommunication/Guids/SystemCommunication.cs
- rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
- rocks.kfs.CustomGroupCommunication/Migrations/001_CreateCommunications.cs
- rocks.kfs.CustomGroupCommunication/Properties/AssemblyInfo.cs
- rocks.kfs.CustomGroupCommunication/rocks.kfs.CustomGroupCommunication.csproj
Adds a job that allows for custom reminder emails to be sent on a group by group basis
* System Communication - System communication to be used for the reminder
* Send Using - Communication Transport to be used for the reminder
* Group Attribute - The attribute on the group that must be set to true to trigger the reminder
---------
New Job that will send reminders to a group based on the Job schedule as long as they are marked with a configured group attribute of type boolean that is set to true.
---------
CBC - Neenah
---------
---------
* rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs - Job
* rocks.kfs.CustomGroupCommunication/Properties/AssemblyInfo.cs - Project definition
* rocks.kfs.CustomGroupCommunication/rocks.kfs.CustomGroupCommunication.csproj …
> Custom Group Reminder Emails

- rocks.kfs.Workflow.Action.Communication/AddSMSConversation.cs
- rocks.kfs.Workflow.Action.Communication/Properties/AssemblyInfo.cs
- rocks.kfs.Workflow.Action.Communication/rocks.kfs.Workflow.Action.Communication.csproj
Added new workflow action to drop a person into SMS conversations and/or display a new custom message for visibility within the SMS conversations block.
- **Message in Conversation**, Message to display in conversation as though it was from the recipient.
- **SMS From Number**, The SMS number the conversation will appear under.
- **Mark as Read**, Flag indicating if the conversation should be marked as read when submitted.
- **Person**, The workflow attribute of the person to be the recipient.
---------
Added new workflow action to drop a person into SMS conversations and/or display a new custom message for visibility within the SMS conversations block.
---------
CBCN
---------
---------
- rocks.kfs.Workflow.Action.Communication/AddSMSConversation.cs
- …
> SMS Conversation Workflow Action

- KFSRock.sln.kfs
- rocks.kfs.GroupRoundRobinAssignment/Jobs/GroupRoundRobinAssignment.cs
- rocks.kfs.GroupRoundRobinAssignment/Properties/AssemblyInfo.cs
- rocks.kfs.GroupRoundRobinAssignment/rocks.kfs.GroupRoundRobinAssignment.csproj
Adds the capability to include family members into the same group when assigning a person from the data view.
---------
- Added support to include family members in the round robin group assignment.
---------
RSC
---------
---------
- KFSRock.sln.kfs
- rocks.kfs.GroupRoundRobinAssignment/Jobs/GroupRoundRobinAssignment.cs
- rocks.kfs.GroupRoundRobinAssignment/rocks.kfs.GroupRoundRobinAssignment.csproj
- rocks.kfs.GroupRoundRobinAssignment/Properties/AssemblyInfo.cs
---------
No
> Round Robin Group Add Job - Family Members

- EventBriteDotNetFramework/Entities/Event.cs
- EventBriteDotNetFramework/Properties/AssemblyInfo.cs
- rocks.kfs.EventBrite/Eventbrite.cs
- rocks.kfs.EventBrite/Field/Types/EventbriteEventFieldType.cs
- rocks.kfs.EventBrite/Properties/AssemblyInfo.cs
- Added protection for saving an invalid token in Eventbrite settings.
- Added additional null checks to prevent exceptions.
- Added additional logic to attempt to match on event/order id/name first prior to adding/matching a new person. This helps address the new Elevated Security level duplicates that can be created. (Fixes #85)
- Fixed the sorting of the orders to help process multiple orders by the same person and/or process refunds/deletes prior to new orders from the same person.
---------
- Added protection for saving an invalid token in Eventbrite settings.
- Added additional null checks to prevent exceptions.
- Added additional logic to attempt to match on event/order id/name first prior to adding/matching a new person.
- Addressed an issue with processing orders from the same …
> Eventbrite Null Checks and Duplicate Prevention

- rocks.kfs.EventBrite/Eventbrite.cs
- rocks.kfs.EventBrite/Properties/AssemblyInfo.cs
Bug fix for when it matches group member but no person, check-in from Eventbrite does not sync properly.
---------
- Fixed bug with Eventbrite check-in no longer working after last update.
---------
Warranty
---------
No
---------
rocks.kfs.EventBrite/Eventbrite.cs
---------
No
> Eventbrite Check-in Fix

- rocks.kfs.Security.ExternalAuthentication.DoorkeeperOAuth/DoorkeeperOAuth.cs
- rocks.kfs.Security.ExternalAuthentication.DoorkeeperOAuth/Properties/AssemblyInfo.cs
- rocks.kfs.Workflow.Action.Communication/AddSMSConversation.cs
- Update workflow action settings to be required, display descriptions (for from number), and update order.
- Add Null checks to DoorkeeperOAuth for address and birthday.
---------
- Update `SMS From Number` to be required.
- Update `SMS From Number` to display descriptions instead of values.
- Added Null checks to DoorkeeperOAuth for address and birthday.
---------
CBC-N, Warranty
---------
---------
- rocks.kfs.Workflow.Action.Communication/AddSMSConversation.cs
- rocks.kfs.Security.ExternalAuthentication.DoorkeeperOAuth/DoorkeeperOAuth.cs
---------
No
> Add SMS Conversation Fix and DoorkeeperOAuth Null Check

- KFSRock.sln.kfs
- rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
- rocks.kfs.Edify/Migrations/001_CreateDefinedTypes.cs
- rocks.kfs.Edify/Properties/AssemblyInfo.cs
- rocks.kfs.Edify/SystemGuid.cs
- rocks.kfs.Edify/packages.config
- rocks.kfs.Edify/rocks.kfs.Edify.csproj
- rocks.kfs.PostalServer/Communications/Transport/PostalServerHTTP.cs
- rocks.kfs.PostalServer/Properties/AssemblyInfo.cs
- rocks.kfs.PostalServer/packages.config
- rocks.kfs.PostalServer/rocks.kfs.PostalServer.csproj
Create Postal Server transport component for Rock via Postal Server API. As well as an Edify.contact specific transport component.
- Base URL
- API Key
---------
- New Rock Transport Component built for Postal Server API
- New Rock Transport Component built for Edify API
---------
Edify.contact
---------
---------
- rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
- rocks.kfs.Edify/Migrations/001_CreateDefinedTypes.cs
- rocks.kfs.Edify/Properties/AssemblyInfo.cs
- rocks.kfs.Edify/SystemGuid.cs
- rocks.kfs.Edify/packages.config
- rocks.kfs.Edify/rocks.kfs.Edify.csproj
- rocks.kfs.PostalServer/Communications/Transport/PostalServerHTTP.cs
- rocks.kfs.PostalServer/Properties/AssemblyInfo.cs
- rocks.kfs.PostalServer/packages.config
- …
> PostalServer Transport Component

- rocks.kfs.Security.ExternalAuthentication.DoorkeeperOAuth/DoorkeeperOAuth.cs
- rocks.kfs.Security.ExternalAuthentication.DoorkeeperOAuth/Properties/AssemblyInfo.cs
Add protection for phone number field potentially being null as well.
---------
- Add protection for phone number field potentially being null as well.
---------
Watermark
---------
No
---------
rocks.kfs.Security.ExternalAuthentication.DoorkeeperOAuth/DoorkeeperOAuth.cs
---------
No
> Doorkeeper Phone Number Null Fix

- rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
- rocks.kfs.Edify/Properties/AssemblyInfo.cs
- rocks.kfs.PostalServer/Communications/Transport/PostalServerHTTP.cs
- rocks.kfs.PostalServer/Properties/AssemblyInfo.cs
Added support for From Name that should have already been there but was missed.
---------
- Added support for From Name field for Edify and Postal Server
---------
Edify
---------
Before:   
After:   
---------
- rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
- rocks.kfs.Edify/Properties/AssemblyInfo.cs
- rocks.kfs.PostalServer/Communications/Transport/PostalServerHTTP.cs
- rocks.kfs.PostalServer/Properties/AssemblyInfo.cs
---------
No
> Update From on Edify and Postal to include FromName.

- rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
- rocks.kfs.Edify/Properties/AssemblyInfo.cs
Fix for Edify if there are attachments don't include Plain Body.
---------
- Fixed issue where an attachment would take over the email in Mac mail and iOS mail in Edify.
---------
Warranty
---------
No
---------
rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
---------
No
> Edify Fix for Attachments

- rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs
- rocks.kfs.StepsToCare/Properties/AssemblyInfo.cs
Round robin assignment only (Care Workers) when "Workers only" is checked for future needs.
---------
- Fixed issue when "Workers Only" is selected only workers should be assigned through the round robin assignment, no small group leaders or "geofence"/deacon workers.
---------
RSC/Warranty
---------
No
---------
rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs
---------
No
> Workers Only Assignment Fix

- rocks.kfs.ShelbyFinancials/Migrations/002_AddDebitAccountSub.cs
- rocks.kfs.ShelbyFinancials/Properties/AssemblyInfo.cs
Migration number 2 for this plugin has a SQL command that potentially inserts AttributeValues for a newly created attribute. The structure of the AttributeValue table added new columns in v14 of Rock that this insert statement did not account for. The INSERT statement has been modified to use explicit column definitions, making it more robust towards potential minor structure changes in the future.
---------
* Fix bug causing exception during plugin migration in Rock v14.
---------
College Church
---------
none
---------
* rocks.kfs.ShelbyFinancials/Migrations/002_AddDebitAccountSub.cs  
---------
no
> ShelbyFinancials - Fix AttributeValue migration to be Rock v14 compatible

- rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
- rocks.kfs.Edify/Properties/AssemblyInfo.cs
- rocks.kfs.PostalServer/Communications/Transport/PostalServerHTTP.cs
- Added an if statement to check for empty email address lists before sending, as apparently the api does accept a list of empty email addresses, just not a null list. Rock does most handling of empty email addresses when it is sent via a communication, but there are some areas in Rock that just adds a recipient even if they don't have an email address, such as the Get Scheduled Payments Job. 
---------
- Fixed an issue where Edify transport could send an empty recipient list to the API.
---------
Warranty, Reported by CCIW
---------
No
---------
- rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
- rocks.kfs.PostalServer/Communications/Transport/PostalServerHTTP.cs
---------
No
> Edify - Handle Empty lists

- rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
- rocks.kfs.Edify/Properties/AssemblyInfo.cs
- rocks.kfs.PostalServer/Communications/Transport/PostalServerHTTP.cs
Fixed incorrect variable for CC and BCC Email lists sent to Edify.
---------
- Fixed incorrect variable for CC and BCC Email lists sent to Edify.
---------
Kensington
---------
No
---------
- rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
- rocks.kfs.Edify/Properties/AssemblyInfo.cs
- rocks.kfs.PostalServer/Communications/Transport/PostalServerHTTP.cs
---------
No
> Edify CC/BCC Fix

- rocks.kfs.WorkflowFromEWS/Jobs/LaunchWorkflowFromEWSAccount.cs
- rocks.kfs.WorkflowFromEWS/Properties/AssemblyInfo.cs
- rocks.kfs.WorkflowFromEWS/rocks.kfs.WorkflowFromEWS.csproj
- Updated to Rock coding standards for job settings
- Renamed Class to "Launch Workflow from EWS Account"
- Added settings to be able to change what messages are selected and how to mark them processed (i.e. flagged messages and remove flag, instead of the default Unread/Read)
- _Launch Workflows With_, What emails should this job use to launch workflows? Default: Unread (When multiple options are selected these are a combined search result, i.e Unread AND Flagged)
- _Mark Processed Emails by_, How should the emails be marked within EWS once they are processed. Default: Read (Note: not all options will work without appropriate permissions. Multiple options will perform all that it can in order presented.)
---------
- Added settings to be able to change what messages are …
> Workflow from EWS changes

- rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
- rocks.kfs.Edify/Properties/AssemblyInfo.cs
Pushing a fix for possible empty email address fix # 2. If CC or BCC is included an empty email address entry was still possible.
---------
- Fixed a potential empty email address email still being allowed to be sent to Edify.
---------
College/Warranty
---------
No
---------
rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs
---------
No
> Edify Possible Empty Email Fix #2

- rocks.kfs.SimpleTexting/rocks.kfs.SimpleTexting.csproj
Missing proper assembly reference to build Simple Texting for v13-14
---------
Missing proper assembly reference to build Simple Texting for v13-14
---------
Warranty
---------
No
---------
rocks.kfs.SimpleTexting/rocks.kfs.SimpleTexting.csproj
---------
No
> Simple Texting v13-14 Fix

- rocks.kfs.FundraisingParticipantSummary/Jobs/FundraisingParticipantSummary.cs
- rocks.kfs.FundraisingParticipantSummary/Properties/AssemblyInfo.cs
Fix job settings that were not supposed to be required on Fundraising Participant summary. Prior to v13, job settings were not required by default, now they are and we need to be explicit when setting them.
---------
Fix job settings that were not supposed to be required on Fundraising Participant summary
---------
Cedar Creek
---------
No longer required as expected:   
---------
- rocks.kfs.FundraisingParticipantSummary/Jobs/FundraisingParticipantSummary.cs
- rocks.kfs.FundraisingParticipantSummary/Properties/AssemblyInfo.cs
---------
No
> Fundraising Participant Summary - Required Job Settings Fix

- rocks.kfs.ShelbyFinancials/Migrations/003_AddCreditCostCenter.cs
- rocks.kfs.ShelbyFinancials/Properties/AssemblyInfo.cs
- rocks.kfs.ShelbyFinancials/SFJournal.cs
- rocks.kfs.ShelbyFinancials/rocks.kfs.ShelbyFinancials.csproj
Added ability to configure specific cost center numbers for credits.
**Attributes:**
- Renamed existing "Cost Center" attribute to "Cost Center Default/Debit"
- Cost Center Credit: New attribute added to Financial Accounts in the Shelby Financials category to allow splitting the cost centers for deposits and credits. 
---------
- Renamed existing "Cost Center" attribute to "Cost Center Default/Debit"
- Added Cost Center Credit attribute to financial accounts in the Shelby Financials category to allow splitting the cost centers for deposits and credits. 
---------
FPG
---------
Attribute Changes:  
---------
* rocks.kfs.ShelbyFinancials/Migrations/003_AddCreditCostCenter.cs
* rocks.kfs.ShelbyFinancials/SFJournal.cs
* rocks.kfs.ShelbyFinancials/rocks.kfs.ShelbyFinancials.csproj
--------- …
> ShelbyFinancials - Add Cost Center Credit support

- rocks.kfs.ShelbyFinancials/Migrations/004_AddTransactionFeeAttributes.cs
- rocks.kfs.ShelbyFinancials/Properties/AssemblyInfo.cs
- rocks.kfs.ShelbyFinancials/SFJournal.cs
- rocks.kfs.ShelbyFinancials/SystemGuid/Attribute.cs
- rocks.kfs.ShelbyFinancials/rocks.kfs.ShelbyFinancials.csproj
Added functionality to configure Financial Gateways to process fees. Also added functionality to group exported lines in different configurations.
---------
See https://github.com/KingdomFirst/RockBlocks/pull/136
---------
Simple Donation
---------
See https://github.com/KingdomFirst/RockBlocks/pull/136
---------
* rocks.kfs.ShelbyFinancials/Migrations/004_AddTransactionFeeAttributes.cs
* rocks.kfs.ShelbyFinancials/SFJournal.cs
* rocks.kfs.ShelbyFinancials/SystemGuid/Attribute.cs
* rocks.kfs.ShelbyFinancials/rocks.kfs.ShelbyFinancials.csproj
---------
https://github.com/KingdomFirst/RockBlocks/pull/136 has dependency
> Shelby Financials - Fee handling and Account Grouping

- rocks.kfs.FundraisingParticipantSummary/Jobs/FundraisingParticipantSummary.cs
- rocks.kfs.FundraisingParticipantSummary/Properties/AssemblyInfo.cs
Fix for "Nullable object must have a value." exception when using just using Group Type.
---------
- Fix for "Nullable object must have a value." exception when using just using Group Type.
---------
Warranty
---------
No
---------
rocks.kfs.FundraisingParticipantSummary/Jobs/FundraisingParticipantSummary.cs
---------
No
> Fundraising Participant Summary Bug fix

- rocks.kfs.Intacct/IntacctCheckingAccountList.cs
- rocks.kfs.Intacct/IntacctEndpoint.cs
- rocks.kfs.Intacct/IntacctJournal.cs
- rocks.kfs.Intacct/IntacctModels.cs
- rocks.kfs.Intacct/IntacctOtherReceipt.cs
- rocks.kfs.Intacct/Properties/AssemblyInfo.cs
- rocks.kfs.Intacct/Utils/TransactionHelpers.cs
Added functionality to group exported lines in different configurations.
---------
[Add a bulleted list of release notes here]
---------
The Father's House
---------
See https://github.com/KingdomFirst/RockBlocks/pull/143
---------
* rocks.kfs.Intacct/IntacctCheckingAccountList.cs
* rocks.kfs.Intacct/IntacctEndpoint.cs
* rocks.kfs.Intacct/IntacctJournal.cs
* rocks.kfs.Intacct/IntacctModels.cs
* rocks.kfs.Intacct/IntacctOtherReceipt.cs
* rocks.kfs.Intacct/Utils/TransactionHelpers.cs
---------
https://github.com/KingdomFirst/RockBlocks/pull/143 has dependency
> Feature - Batch To Intacct Account Grouping

- rocks.kfs.GroupRoundRobinAssignment/Jobs/GroupRoundRobinAssignment.cs
- rocks.kfs.GroupRoundRobinAssignment/Properties/AssemblyInfo.cs
Added additional settings for disabling campus requirement, removing group members and outputting errors to job history. Also fixed an issue that wouldn't check for family members in existing groups when being added. (Fixes #116)
- **Output Errors to History**, Should the job output all errors to job history? Default: Yes
- **Remove Members not in Data View**, Should the job automatically remove group members not in the Data View? (Note: if you 'Include Family Members' your Data View should include them to prevent them from being removed with this setting.) Default: No
- **Use Group Campus**, Should the job use Group Campus to match groups to person campus when assigning people to groups? Default: Yes
---------
- Added additional settings for disabling campus …
> Group Round Robin Assignment Changes

- rocks.kfs.Intacct/IntacctJournal.cs
- rocks.kfs.Intacct/IntacctModels.cs
- rocks.kfs.Intacct/IntacctOtherReceipt.cs
- rocks.kfs.Intacct/Migrations/001_AddSystemData.cs
- rocks.kfs.Intacct/Migrations/002_AddTransactionFeeAttributes.cs
- rocks.kfs.Intacct/Migrations/003_AddBatchesToIntacct.cs
- rocks.kfs.Intacct/Migrations/004_AddDebitAccountAttributes.cs
- rocks.kfs.Intacct/Properties/AssemblyInfo.cs
- rocks.kfs.Intacct/SystemGuid/Attribute.cs
- rocks.kfs.Intacct/Utils/TransactionHelpers.cs
- rocks.kfs.Intacct/rocks.kfs.Intacct.csproj
Added new debit account specific classification attributes and support for grouping by them. Also added support for grouping by custom dimensions when using a GL account grouping mode.
**New Attributes:**
- Default Debit Project
- Debit Class
- Debit Department
- Debit Location
---------
See https://github.com/KingdomFirst/RockBlocks/pull/147
---------
The Father's House
---------
Financial Account Attribute Changes:  
---------
* rocks.kfs.Intacct/IntacctJournal.cs
* rocks.kfs.Intacct/IntacctModels.cs
* rocks.kfs.Intacct/IntacctOtherReceipt.cs
* rocks.kfs.Intacct/Migrations/001_AddSystemData.cs
* rocks.kfs.Intacct/Migrations/002_AddTransactionFeeAttributes.cs
* rocks.kfs.Intacct/Migrations/003_AddBatchesToIntacct.cs
* rocks.kfs.Intacct/Migrations/004_AddDebitAccountAttributes.cs
* …
> F: BatchToIntacct - Add support for debit specific attributes

- KFSRock.sln.kfs
- rocks.kfs.RoundRobinGroupAssignment/Jobs/RoundRobinGroupAssignment.cs
- rocks.kfs.RoundRobinGroupAssignment/Properties/AssemblyInfo.cs
- rocks.kfs.RoundRobinGroupAssignment/rocks.kfs.RoundRobinGroupAssignment.csproj
Rename everything to RoundRobinGroupAssignment
---------
Rename everything to RoundRobinGroupAssignment
---------
College
---------
---------
- KFSRock.sln.kfs
- rocks.kfs.RoundRobinGroupAssignment/Jobs/RoundRobinGroupAssignment.cs
- rocks.kfs.RoundRobinGroupAssignment/Properties/AssemblyInfo.cs
- rocks.kfs.RoundRobinGroupAssignment/rocks.kfs.RoundRobinGroupAssignment.csproj
---------
Yes, any dev environments will need to be updated with new sln file or re-locate the new project in current solution.
> Rename to Round Robin Group Assignment

- rocks.kfs.Microsoft365Utilities/Properties/AssemblyInfo.cs
- rocks.kfs.Microsoft365Utilities/Shortcodes/CalendarItemsShortcode.cs
- rocks.kfs.Microsoft365Utilities/rocks.kfs.Microsoft365Utilities.csproj
EWS Calendar Shortcode updated to use Fluid in v13+
---------
- Updated EWS Calendar Shortcode to be supported with Fluid lava engine.
---------
Warranty
---------
No
---------
- rocks.kfs.Microsoft365Utilities/Properties/AssemblyInfo.cs
- rocks.kfs.Microsoft365Utilities/Shortcodes/CalendarItemsShortcode.cs
- rocks.kfs.Microsoft365Utilities/rocks.kfs.Microsoft365Utilities.csproj
---------
v13+ only
> EWS Fluid Shortcode v13+

- rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
- rocks.kfs.CustomGroupCommunication/Properties/AssemblyInfo.cs
Update version to rebuild for v14+ with new iCal reference and found a bug that it was not actually honoring no/false on the attribute.
---------
- Fixed a reference exception when running with v14+ of Rock. (Fixes #136)
- Updated logic to honor "no" on the boolean attribute.
---------
Warranty
---------
No
---------
- rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs
- rocks.kfs.CustomGroupCommunication/Properties/AssemblyInfo.cs
---------
Yes, technically 14+ only will have the fix for the boolean "no/false" and has to have a specific dll build for version support.
> Group Meeting Reminders v14+ Build and Bug fix

- rocks.kfs.FinancialEdge/Migrations/004_AddContextAttribute.cs
- rocks.kfs.FinancialEdge/Properties/AssemblyInfo.cs
- rocks.kfs.FinancialEdge/rocks.kfs.FinancialEdge.csproj
- rocks.kfs.Intacct/Migrations/005_AddContextAttribute.cs
- rocks.kfs.Intacct/Properties/AssemblyInfo.cs
- rocks.kfs.Intacct/rocks.kfs.Intacct.csproj
- rocks.kfs.ShelbyFinancials/Migrations/005_AddContextAttribute.cs
- rocks.kfs.ShelbyFinancials/Properties/AssemblyInfo.cs
- rocks.kfs.ShelbyFinancials/rocks.kfs.ShelbyFinancials.csproj
Added ContextAware to all of our financial plugin blocks for future version support with hashed id's. 
---------
- Added context support to blocks and default attribute values via migrations.
---------
MHC, Warranty
---------
No
---------
- rocks.kfs.FinancialEdge/Migrations/004_AddContextAttribute.cs
- rocks.kfs.FinancialEdge/Properties/AssemblyInfo.cs
- rocks.kfs.FinancialEdge/rocks.kfs.FinancialEdge.csproj
- rocks.kfs.Intacct/Migrations/005_AddContextAttribute.cs
- rocks.kfs.Intacct/Properties/AssemblyInfo.cs
- rocks.kfs.Intacct/rocks.kfs.Intacct.csproj
- rocks.kfs.ShelbyFinancials/Migrations/005_AddContextAttribute.cs
- rocks.kfs.ShelbyFinancials/Properties/AssemblyInfo.cs
- rocks.kfs.ShelbyFinancials/rocks.kfs.ShelbyFinancials.csproj
---------
Technically no, this is better …
> Financial context update

- rocks.kfs.Intacct/IntacctJournal.cs
- rocks.kfs.Intacct/Properties/AssemblyInfo.cs
Fix for negative transaction fees again. Similar to #82 but in the new code
---------
- Fixed an issue that refunded transaction fees would not export properly to Intacct.
---------
Warranty
---------
No
---------
rocks.kfs.Intacct/IntacctJournal.cs
---------
No
> Intacct Negative Transaction Fee Fix

- .gitignore
- rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs
- rocks.kfs.StepsToCare/Migrations/022_UpdateCommunications.cs
- rocks.kfs.StepsToCare/Model/TouchTemplate.cs
- rocks.kfs.StepsToCare/Properties/AssemblyInfo.cs
- rocks.kfs.StepsToCare/Utilities.cs
- rocks.kfs.StepsToCare/rocks.kfs.StepsToCare.csproj
- Update Custom Follow Up Unsnooze parameters, shouldn't require Custom Follow Up any longer.
- Update System Communications with a generic "Take Action" button and person token's on links.
---------
- Update Custom Follow Up Unsnooze parameters, shouldn't require Custom Follow Up any longer.
- Update System Communications with a generic "Take Action" button and person token's on links.
---------
CBCN
---------
---------
- rocks.kfs.StepsToCare/rocks.kfs.StepsToCare.csproj
- rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs
- rocks.kfs.StepsToCare/Migrations/022_UpdateCommunications.cs
---------
No, though we do update system communications, so any changes by users could be overwritten.
> Steps to Care, Minor Job Updates and new Migration

- rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs
Somehow missed identifying notetemplate's by Guid's in the job.
---------
- Fixed an issue that certain notes were not being included in the touch count in Care Touch Needed Notification.
---------
CBCN/Warranty
---------
No
---------
rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs
---------
No
> Steps to Care Minor Bug

- rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs
Minimum touch count should be less than only, not less than or equal to what you set, dashboard block does it right, just not the notification...
---------
Not released yet, bug fix.
---------
Warranty
---------
No
---------
rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs
---------
No
> Minor Steps to Care Job Update

- rocks.kfs.CyberSource/Gateway.cs
- rocks.kfs.CyberSource/Properties/AssemblyInfo.cs
- rocks.kfs.JavaScript.Obsidian/src/Controls/cyberSourceGatewayControl.obs
Add Event Registration Address Mode setting to Gateway and control.
_Event Registration Address Mode_, The mode for address input on the Gateway with event registrations. In order to use 'Hide' or 'Optional' you must have Relaxed AVS enabled by the processor.
---------
Added new Gateway setting "Event Registration Address Mode"
---------
Island
---------
---------
- rocks.kfs.CyberSource/Gateway.cs
- rocks.kfs.JavaScript.Obsidian/src/Controls/cyberSourceGatewayControl.obs
---------
No
> Cybersource Gateway Update - Event Registration Address Mode

- rocks.kfs.Intacct/IntacctJournal.cs
- rocks.kfs.Intacct/IntacctModels.cs
- rocks.kfs.Intacct/Properties/AssemblyInfo.cs
Fixed issue reported after previous update affecting order of gl entry lines in non-grouped situations
---------
* Fixed bug introduced in previous release causing undesired change in journal entry lines when special grouping is not configured.
---------
Kensington Church
---------
Example of journal entry line order *before* changes:  
Example of journal entry line order *after* changes:  
---------
* rocks.kfs.Intacct/IntacctJournal.cs
* rocks.kfs.Intacct/IntacctModels.cs
---------
no
> Batch to Intacct - Fixed bug with ordering of debit and credit lines

- rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupEmail.cs
- rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupSMS.cs
- rocks.kfs.ScheduledGroupCommunication/Properties/AssemblyInfo.cs
- Add two additional CommandTimeout set points. 
- Remove unnecessary query on each recipient for ScheduledGroupSMS.
---------
- Fixed a bug with Send Scheduled Group SMS reloading each recipient and causing unnecessary database calls.
---------
KCC
---------
No
---------
- rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupEmail.cs
- rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupSMS.cs
---------
No, though only tested v16.3+.
> Scheduled Group Communication Bug

- rocks.kfs.ShelbyFinancials/Migrations/006_AddDebitAccountAttributes.cs
- rocks.kfs.ShelbyFinancials/Properties/AssemblyInfo.cs
- rocks.kfs.ShelbyFinancials/SFJournal.cs
- rocks.kfs.ShelbyFinancials/SystemGuid/Attribute.cs
- rocks.kfs.ShelbyFinancials/rocks.kfs.ShelbyFinancials.csproj
* Added support for applying different projects for debits vs. credits for FinancialAccounts.  
* Added ProjectMode functionality to allow applying project codes descriminantly to credit and/or debit lines.
---------
[Add a bulleted list of release notes here]
---------
Hill Country Bible Church
---------
Debit and Credit specific project attributes  
---------
* rocks.kfs.ShelbyFinancials/Migrations/006_AddDebitAccountAttributes.cs
* rocks.kfs.ShelbyFinancials/SFJournal.cs
* rocks.kfs.ShelbyFinancials/SystemGuid/Attribute.cs
* rocks.kfs.ShelbyFinancials/rocks.kfs.ShelbyFinancials.csproj
---------
https://github.com/KingdomFirst/RockBlocks/pull/189 has dependency.
> Shelby Financials Batch To Journal

- rocks.kfs.StepsToCare/Properties/AssemblyInfo.cs
- rocks.kfs.StepsToCare/Utilities.cs
Fixed https://github.com/KingdomFirst/RockAssemblies/issues/170
---------
* Fixed bug causing unpredictable results when workers are auto-assigned based on load balancing based on group membership when multiple members have zero care needs assigned to them that are not Closed.
---------
Warranty/Bug
---------
no
---------
* rocks.kfs.StepsToCare/Utilities.cs
---------
no
> Steps To Care Auto Assign Worker Bug Fix

- rocks.kfs.CyberSource/Configuration.cs
- rocks.kfs.CyberSource/Controls/CyberSourceHostedPaymentControl.cs
- rocks.kfs.CyberSource/Gateway.cs
- rocks.kfs.CyberSource/Model/FlexCaptureContextPayload.cs
- rocks.kfs.CyberSource/Properties/AssemblyInfo.cs
- rocks.kfs.JavaScript.Obsidian/package-lock.json
- rocks.kfs.JavaScript.Obsidian/src/Controls/cyberSourceGatewayControl.obs
- Update to add a new setting for "Allowed Card Networks" now that CyberSource is enforcing allowed values.
- Also updated microform script declaration based on v2 guidelines released this year.
_Allowed Card Networks_, The allowed card networks supported by this gateway.
---------
- Update to add a new setting for "Allowed Card Networks" now that CyberSource is enforcing allowed values.
---------
Warranty
---------
New setting:   
---------
- rocks.kfs.JavaScript.Obsidian/src/Controls/cyberSourceGatewayControl.obs
- rocks.kfs.CyberSource/Model/FlexCaptureContextPayload.cs
- rocks.kfs.CyberSource/Gateway.cs
- rocks.kfs.CyberSource/Controls/CyberSourceHostedPaymentControl.cs
- rocks.kfs.CyberSource/Configuration.cs
---------
No
> Cyber Source Gateway Update
