rocks.kfs.ShelbyFinancials/SFJournal.cs
Enable lava support for the Journal Description column. Specifically with the request of wanting to include Registration information in the description.
Assembly changes for https://github.com/KingdomFirst/RockBlocks/pull/5
---------
**Shelby Financials**
- Added lava support for the Journal Description Column
---------
FPG
---------
See https://github.com/KingdomFirst/RockBlocks/pull/5
---------
- rocks.kfs.ShelbyFinancials/SFJournal.cs
---------
Yes, requires Block Update. https://github.com/KingdomFirst/RockBlocks/pull/5
=> Shelby Financials Lava Update 

rocks.kfs.ShelbyFinancials/Properties/AssemblyInfo.cs, rocks.kfs.ShelbyFinancials/SFJournal.cs
Forgot a couple merge fields and new version for assembly.
---------
- Forgot a couple merge fields and new version for assembly.
---------
FPG
---------
No
---------
- rocks.kfs.ShelbyFinancials/Properties/AssemblyInfo.cs
- rocks.kfs.ShelbyFinancials/SFJournal.cs
---------
No
=> Forgot a couple merge fields and new version for assembly.

rocks.kfs.Reach/Gateway.cs
Added project title trim and decided to do it on categories as well so that it matches better with defined type values.
---------
* Added white space trimming to project and category titles.
---------
Kensington
---------
No
---------
rocks.kfs.Reach/Gateway.cs
---------
No
=> Reach Gateway Trim Data

rocks.kfs.CampusEngagementEmailSend/Jobs/CampusEngagementEmailSend.cs, rocks.kfs.CampusEngagementEmailSend/Properties/AssemblyInfo.cs, rocks.kfs.CampusEngagementEmailSend/rocks.kfs.CampusEngagementEmailSend.csproj, rocks.kfs.GroupRoleAttendanceReminder/rocks.kfs.GroupRoleAttendanceReminder.csproj
**Thank you for your code contribution, we will take your code suggestion into consideration. It will be reviewed, and based on code quality and need addressed, we will determine acceptance. If this code addresses a feature request or issue, be sure to link to that issue.** 
Creates a job that sends a system email hydrated with group data (from a selected list of group types) to each campus pastor.
* Group Types
---------
* Adds the CampusEngagementEmailSend job that hydrates a system email with group information.
---------
City First Church
---------
---------
* rocks.kfs.CampusEngagementEmailSend/Jobs/CampusEngagementEmailSend.cs
* rocks.kfs.CampusEngagementEmailSend/Properties/AssemblyInfo.cs
* rocks.kfs.CampusEngagementEmailSend/rocks.kfs.CampusEngagementEmailSend.csp …
=> Campus Engagement Email Job

rocks.kfs.FundraisingParticipantSummary/Jobs/FundraisingParticipantSummary.cs
Updated setting to use a Group Picker instead of GroupTypeGroup field.
---------
None
---------
Kensington 
---------
Maybe
---------
rocks.kfs.FundraisingParticipantSummary/Jobs/FundraisingParticipantSummary.cs
---------
No
=> Fundraising Participants Setting Change

rocks.kfs.ShelbyBatchExport/Migrations/001_CreateShelbyGLAssets.cs, rocks.kfs.ShelbyBatchExport/Migrations/002_ProjectsPage.cs, rocks.kfs.ShelbyBatchExport/Migrations/003_BatchExportDetailsBlock.cs, rocks.kfs.ShelbyBatchExport/Migrations/004_TransitionFromCodeAttribute.cs
Update all Guids to be unique for Shelby GL Export Plugin. Primarily for dev environments running both Shelby GL Export and Shelby Financials.
---------
N/A
---------
Warranty
---------
No
---------
- rocks.kfs.ShelbyBatchExport/Migrations/001_CreateShelbyGLAssets.cs
- rocks.kfs.ShelbyBatchExport/Migrations/002_ProjectsPage.cs
- rocks.kfs.ShelbyBatchExport/Migrations/003_BatchExportDetailsBlock.cs
- rocks.kfs.ShelbyBatchExport/Migrations/004_TransitionFromCodeAttribute.cs
---------
No
=> Shelby GL Export Unique Guids

rocks.kfs.RoomManagement.Templates/LavaLandscapeReportTemplate.cs, rocks.kfs.RoomManagement.Templates/SPACReportTemplate.cs
v10 changes for Room Management Report Ambiguous Reference Fix.
---------
Room Management Report Ambiguous Reference Fix
---------
Warranty
---------
No
---------
- rocks.kfs.RoomManagement.Templates/LavaLandscapeReportTemplate.cs
- rocks.kfs.RoomManagement.Templates/SPACReportTemplate.cs
---------
No
=> Room Management Report Ambiguous Reference Fix

rocks.kfs.Vimeo/Video.cs
Null reference exception fix if description is empty.
---------
- Fixed Null reference exception if description is empty.
---------
Whitewater Crossing
---------
No
---------
rocks.kfs.Vimeo/Video.cs
---------
No
=> Vimeo Sync Null Reference Fix

rocks.kfs.RoomManagement.Templates/rocks.kfs.RoomManagement.ReportTemplates.csproj
Typo when a SpecificVersion reference was added to a csproj file
---------
None
---------
Warranty	
---------
No
---------
rocks.kfs.RoomManagement.Templates/rocks.kfs.RoomManagement.ReportTemplates.csproj
---------
No
=> CSProject Typo fix

KFSRock.sln.kfs
SLN File Test
---------
No
---------
Us
---------
No
---------
KFSRock.sln.kfs
---------
No
=> KFS SLN file test

rocks.kfs.Reach/Properties/AssemblyInfo.cs, rocks.kfs.Reach/Reporting/Api.cs, rocks.kfs.Reach/rocks.kfs.Reach.csproj
Changes for country validation that Rock added in v12
---------
* Changes for country validation that Rock added in v12
---------
Kensington
---------
No
---------
- rocks.kfs.Reach/Properties/AssemblyInfo.cs
- rocks.kfs.Reach/Reporting/Api.cs
- rocks.kfs.Reach/rocks.kfs.Reach.csproj
---------
No
=> Reach Country Validation Changes

EventBriteDotNetFramework/Entities/Event.cs, EventBriteDotNetFramework/Properties/AssemblyInfo.cs
Eventbrite API Change update for description field being removed and summary being added.
---------
Eventbrite API Change update for description field being removed and summary being added.
---------
Kensington
---------
No
---------
- EventBriteDotNetFramework/Entities/Event.cs
- EventBriteDotNetFramework/Properties/AssemblyInfo.cs
---------
Yes, requires block update from https://github.com/KingdomFirst/RockBlocks/pull/49
=> Eventbrite API Change

rocks.kfs.ScheduledGroupCommunication/ReadMe.md
Scheduled Group Communications ReadMe.md
Created/Updated Scheduled Group Communications ReadMe.md from Rock Shop documentation
---------
Created/Updated Scheduled Group Communications ReadMe.md from Rock Shop documentation
---------
Support
---------
No
---------
rocks.kfs.ScheduledGroupCommunication/ReadMe.md
---------
No
=> Scheduled Group Communications ReadMe

rocks.kfs.ScheduledGroupCommunication/ReadMe.md
**Thank you for your code contribution, we will take your code suggestion into consideration. It will be reviewed, and based on code quality and need addressed, we will determine acceptance. If this code addresses a feature request or issue, be sure to link to that issue.** 
Scheduled Group Communications ReadMe.md
Created/Updated Scheduled Group Communications ReadMe.md from Rock shop documentation
- Created/Updated Scheduled Group Communications ReadMe.md from Rock shop documentation
---------
Support
---------
No
---------
RockAssemblies/rocks.kfs.ScheduledGroupCommunication/ScheduledGroupCommunicationsReadMe.md 
---------
No
=> Update Scheduled Group Communication ReadMe.md

rocks.kfs.StepsToCare/Migrations/001_CreateDb.cs, rocks.kfs.StepsToCare/Migrations/002_CreateDefinedTypes.cs, rocks.kfs.StepsToCare/Migrations/003_CreateCommunications.cs, rocks.kfs.StepsToCare/Migrations/004_CreatePages.cs, rocks.kfs.StepsToCare/Migrations/005_CreateJob.cs, rocks.kfs.StepsToCare/Migrations/006_AddWorkersOnlyColumn.cs, rocks.kfs.StepsToCare/Migrations/007_CreateAttribute.cs, rocks.kfs.StepsToCare/Migrations/008_LavaShortcode.cs, rocks.kfs.StepsToCare/Migrations/009_CreatePermissions.cs
For some reason I missed the namespace was wrong on Steps to Care migrations.
=> Steps to Care Namespace update for migrations

rocks.kfs.Shortcodes/EWS/CalendarItems.cs, rocks.kfs.Shortcodes/Migrations/001_CreateAttribute.cs, rocks.kfs.Shortcodes/Properties/AssemblyInfo.cs, rocks.kfs.Shortcodes/rocks.kfs.Shortcodes.csproj, rocks.kfs.WorkflowFromEWS/rocks.kfs.WorkflowFromEWS.csproj
New custom lava shortcode for pulling outlook mailbox appointments/meetings from a Microsoft Exchange server using EWS managed API.
All new settings
---------
New custom lava shortcode for pulling outlook mailbox appointments/meetings from a Microsoft Exchange server using EWS managed API.
---------
New Hope Church
---------
New Global Attributes created with Migration:  
EWS Calendar Items shortcode:  
---------
* rocks.kfs.Shortcodes/EWS/CalendarItems.cs
* rocks.kfs.Shortcodes/Migrations/001_CreateAttribute.cs
* rocks.kfs.Shortcodes/Properties/AssemblyInfo.cs
* rocks.kfs.Shortcodes/rocks.kfs.Shortcodes.csproj]
---------
v12 only. Will need updated to work with v13 lava
=> New KFS Shortcodes library with new EWSCalendarItems shortcode

rocks.kfs.Zoom/Migrations/005_CreateJobs.cs
Exception when running Zoom migration for the first time.
---------
Exception when running Zoom migration for the first time.
---------
FPG
---------
No
---------
rocks.kfs.Zoom/Migrations/005_CreateJobs.cs
---------
No
=> Zoom Migration Issue

rocks.kfs.StepsToCare/Migrations/010_AddParentNeedId.cs
Steps to Care Migration Issue
(cherry picked from commit 61c0d876306d90299b3676b0ed8e4055f5526ba5)
=> Cherry Pick Into hotfix-12 - Merge pull request #66 from KingdomFirst/bug/nbh-StepsToCare

rocks.kfs.StepsToCare/Migrations/012_NewBlockSettings.cs
Cherry Picked from https://github.com/KingdomFirst/RockAssemblies/pull/68 into hotfix-12
=> Cherry Pick #68 into hotfix-12

rocks.kfs.Zoom/Migrations/001_CreateDb.cs
ZoomRoom Migration Fix v12
(cherry picked from commit aac35c7d991a8860af14674cbc86f317ddfb1874)
=> Cherry-pick into master - Merge pull request #70 from KingdomFirst/bug/ZoomRoomMigrationFix_v12

rocks.kfs.Zoom/Model/RoomOccurrence.cs
Revert v13 dependent changes for Zoom.
---------
Revert v13 dependent changes for Zoom.
---------
Warranty
---------
No
---------
rocks.kfs.Zoom/Model/RoomOccurrence.cs
---------
No
=> Revert v13 dependent changes for Zoom.

rocks.kfs.StepsToCare/Migrations/013_NewPermissions.cs, rocks.kfs.StepsToCare/Migrations/014_NewPageAndAttributes.cs, rocks.kfs.StepsToCare/rocks.kfs.StepsToCare.csproj
Merge pull request #73 from KingdomFirst/feature/nbh-StepsToCareNewPermissions
Steps to Care New Migrations for permissions and new page
(cherry picked from commit ee2f34accc32fae649751922a6b2c915f0a67993) 
Original Pull Request #73
=> Cherry Pick - Merge pull request #73

rocks.kfs.Checkin.PagerEntry/Migrations/001_PagerEntryInstall.cs, rocks.kfs.Checkin.PagerEntry/Properties/AssemblyInfo.cs, rocks.kfs.Checkin.PagerEntry/rocks.kfs.Checkin.PagerEntry.csproj
Pager Entry Migration
(cherry picked from commit bb5d16c057aa470f96f7a0a00bf229fcec6d1edc)
=> Cherry-pick - Merge pull request #76 from KingdomFirst/feature/nbh-PagerEntryMigration

rocks.kfs.Checkin.PagerEntry/Migrations/002_PagerEntryUpdate.cs, rocks.kfs.Checkin.PagerEntry/Properties/AssemblyInfo.cs, rocks.kfs.Checkin.PagerEntry/rocks.kfs.Checkin.PagerEntry.csproj, rocks.kfs.Intacct/IntacctJournal.cs, rocks.kfs.Intacct/Utils/TransactionHelpers.cs, rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs, rocks.kfs.StepsToCare/Migrations/015_UpdateJob.cs, rocks.kfs.StepsToCare/Model/WorkerResult.cs, rocks.kfs.StepsToCare/Properties/AssemblyInfo.cs, rocks.kfs.StepsToCare/Utilities.cs, rocks.kfs.StepsToCare/rocks.kfs.StepsToCare.csproj
Cherry Pick - v13 #80, #82, #83
=> Cherry Pick - v13 #80, #82, #83

KFSRock.sln.kfs, rocks.kfs.CustomGroupCommunication/Guids/SystemCommunication.cs, rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs, rocks.kfs.CustomGroupCommunication/Migrations/001_CreateCommunications.cs, rocks.kfs.CustomGroupCommunication/Properties/AssemblyInfo.cs, rocks.kfs.CustomGroupCommunication/rocks.kfs.CustomGroupCommunication.csproj, rocks.kfs.Zoom/Migrations/008_MakeCommunicationsEditable.cs, rocks.kfs.Zoom/Properties/AssemblyInfo.cs, rocks.kfs.Zoom/rocks.kfs.Zoom.csproj
Merge pull request #86 from KingdomFirst/feature/CustomGroupReminderEmails
Custom Group Reminder Emails
(cherry picked from commit 70c81b4a10af74e2faf6382a7439df62d987bfdd)
Merge pull request #88 from KingdomFirst/bug/ZoomCommunicationsEditable
Zoom Reminders Editable
(cherry picked from commit 6be8d006e48e1a9c0e51030dbea7bd798c157679)
=> Cherry pick - #86 and #88

rocks.kfs.SimpleTexting/Communications/Transport/SimpleTexting.cs, rocks.kfs.SimpleTexting/Properties/AssemblyInfo.cs, rocks.kfs.SimpleTexting/packages.config, rocks.kfs.SimpleTexting/rocks.kfs.SimpleTexting.csproj
- Added new Communication Transport for Simple Texting
---------
- Added new Communication Transport for Simple Texting
---------
VWC
---------
---------
- rocks.kfs.SimpleTexting/Communications/Transport/SimpleTexting.cs
- rocks.kfs.SimpleTexting/Properties/AssemblyInfo.cs
- rocks.kfs.SimpleTexting/rocks.kfs.SimpleTexting.csproj
---------
No
=> SimpleTexting Communication Transport

KFSRock.sln.kfs
Forgot to update KFS SLN with new assembly in prior merge requests.
=> Forgot to update KFS SLN with new assembly in prior merge requests.

rocks.kfs.FundraisingParticipantSummary/Jobs/FundraisingParticipantSummary.cs, rocks.kfs.FundraisingParticipantSummary/Properties/AssemblyInfo.cs
* Update job setting logic to current coding standards.
* Added verbose logging functionality.
* Added Command Timeout Override setting.
* Restructured exception and error handling for better reporting.
* Command Timeout Override.  
* Verbose Logging setting for enabling detailed logging.
---------
* Added verbose logging functionality.
* Added Command Timeout Override setting.
* Restructured exception and error handling for better reporting.
---------
Kensington Church
---------
Example warning (completed with errors):
Example hard fail (no emails sent due to errors):
---------
* rocks.kfs.FundraisingParticipantSummary/Jobs/FundraisingParticipantSummary.cs  
---------
no
=> Fundraising Participant Summary fix

KFSRock.sln.kfs, rocks.kfs.DashboardsAndMetrics/rocks.kfs.DashboardsAndMetrics.csproj
Update dashboards and metrics migration for .NET 4.7.2 and new Rock common helpers.
---------
Update dashboards and metrics migration for .NET 4.7.2 and new Rock common helpers
---------
Warranty
---------
Proof it ran migration on dev environment:    
---------
- rocks.kfs.DashboardsAndMetrics/rocks.kfs.DashboardsAndMetrics.csproj
- KFSRock.sln.kfs
---------
No
=> Dashboard and Metrics v14

rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupEmail.cs, rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupSMS.cs, rocks.kfs.ScheduledGroupCommunication/Properties/AssemblyInfo.cs
Fixed a minor performance issue causing job to potentially fail with timeout exception for large AttributeValue tables.
---------
- Fixed a minor performance issue causing job to potentially fail with timeout exception for large AttributeValue tables.
---------
Warranty
---------
none
---------
* rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupEmail.cs
* rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupSMS.cs
---------
no
=> B: Scheduled Group Communication plugin

rocks.kfs.GroupRoundRobinAssignment/Jobs/GroupRoundRobinAssignment.cs
Update GroupRoundRobinAssignment.cs, minor setting description change.
=> Group Round Robin Setting Update

rocks.kfs.RoundRobinGroupAssignment/Jobs/RoundRobinGroupAssignment.cs
Update error message handling in Round Robin Group Assignment.
---------
- Update error message handling in Round Robin Group Assignment
---------
College
---------
No
---------
- rocks.kfs.RoundRobinGroupAssignment/Jobs/RoundRobinGroupAssignment.cs
---------
No
=> Round Robin Group Assignment Error Msg 

rocks.kfs.EventBrite/Eventbrite.cs, rocks.kfs.EventBrite/Field/Types/EventbritePersonFieldType.cs, rocks.kfs.EventBrite/Migrations/001_Init.cs, rocks.kfs.EventBrite/Properties/AssemblyInfo.cs
- Fixed an issue with our Eventbrite Person field type on the group member list by making it a proper filter now.
- Fixed an issue with Ticket quantities not being counted properly when there were multiple orders for the same person.
---------
- Fixed an issue with our Eventbrite Person field type on the group member list by making it a proper filter now.
- Fixed an issue with Ticket quantities not being counted properly when there were multiple orders for the same person.
---------
Warranty
---------
---------
- rocks.kfs.EventBrite/Eventbrite.cs
- rocks.kfs.EventBrite/Field/Types/EventbritePersonFieldType.cs
---------
No, though we recommend re-syncing your groups if you want valid ticket quantities on each group member.
=> Eventbrite Bug Fixes

KFSRock.sln.kfs, README.md, ZZZ_Archive/rocks.kfs.Edify/rocks.kfs.Edify.csproj, ZZZ_Archive/rocks.kfs.PostalServer/rocks.kfs.PostalServer.csproj, rocks.kfs.GroupRoleAttendanceReminder/rocks.kfs.GroupRoleAttendanceReminder.csproj, rocks.kfs.RoundRobinGroupAssignment/rocks.kfs.RoundRobinGroupAssignment.csproj, rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupEmail.cs, rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupSMS.cs, rocks.kfs.ScheduledGroupCommunication/Migrations/004_SystemPhoneSupport.cs, rocks.kfs.ScheduledGroupCommunication/Properties/AssemblyInfo.cs, rocks.kfs.ScheduledGroupCommunication/SystemGuid/Attribute.cs, rocks.kfs.ScheduledGroupCommunication/rocks.kfs.ScheduledGroupCommunication.csproj, rocks.kfs.SimpleTexting/rocks.kfs.SimpleTexting.csproj, rocks.kfs.Workflow.Action.Cms/rocks.kfs.Workflow.Action.Cms.csproj, rocks.kfs.Workflow.Action.Core/rocks.kfs.Workflow.Action.Core.csproj, rocks.kfs.Zoom/rocks.kfs.Zoom.csproj
Now that v15 has gone Generally Available, it is time to takeover master/development. Code will need to be reviewed carefully and clients will be taken into consideration if they are not on v15 just yet.
---------
Rock Version 15 is now generally available. All code will be updated to support 15+ only.
---------
Warranty
---------
No
---------
See Files changed tab.
---------
Yes, v14 and below will no longer be supported by ongoing development.
=> Version 15 Release

rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs, rocks.kfs.StepsToCare/Properties/AssemblyInfo.cs
Filter out snoozed status from notifications and add a setting for Outstanding Needs notification.
_Outstanding Needs Include Snoozed_, How should snoozed needs be handled in the Outstanding Needs notification?
---------
- Filter out snoozed status from notifications and add a setting for Outstanding Needs notification.
---------
Warranty
---------
---------
rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs
---------
No
=> Steps to Care Snoozed Notifications Fix

.gitignore, KFSRock.sln.kfs, rocks.kfs.CyberSource/Configuration.cs, rocks.kfs.CyberSource/Controls/CyberSourceHostedPaymentControl.cs, rocks.kfs.CyberSource/Gateway.cs, rocks.kfs.CyberSource/Model/AddressToken.cs, rocks.kfs.CyberSource/Properties/AssemblyInfo.cs, rocks.kfs.CyberSource/rocks.kfs.CyberSource.csproj, rocks.kfs.JavaScript.Obsidian/.eslintrc.js, rocks.kfs.JavaScript.Obsidian/.gitignore, rocks.kfs.JavaScript.Obsidian/.vscode/launch.json, rocks.kfs.JavaScript.Obsidian/PROJECT_MIGRATION_LOG.txt, rocks.kfs.JavaScript.Obsidian/build/.eslintrc.js, rocks.kfs.JavaScript.Obsidian/build/build-fast.js, rocks.kfs.JavaScript.Obsidian/build/build-types.js, rocks.kfs.JavaScript.Obsidian/jest.config.js, rocks.kfs.JavaScript.Obsidian/nuget.config, rocks.kfs.JavaScript.Obsidian/package-lock.json, rocks.kfs.JavaScript.Obsidian/package.json, rocks.kfs.JavaScript.Obsidian/rocks.kfs.JavaScript.Obsidian.esproj, rocks.kfs.JavaScript.Obsidian/rocks.kfs.JavaScript.Obsidian.njsproj, rocks.kfs.JavaScript.Obsidian/rollup.config.js, rocks.kfs.JavaScript.Obsidian/src/Controls/cyberSourceGatewayControl.obs, rocks.kfs.JavaScript.Obsidian/tests/tsconfig.json, rocks.kfs.JavaScript.Obsidian/tsconfig.json
- Added Cybersource ObsidianHostedGateway changes.
- Added new Javascript.Obsidian project for building Obsidian controls, specifically for the Gateway for now.
---------
- Added Cybersource ObsidianHostedGateway changes.
---------
Island
---------
Updated to include address:   
New generic error message added (will still log the exception with full error):   
(Valid test credit card, but Gateway does not accept Discover cards.)
(Actual exception isn't very helpful in this context...)
---------
- .gitignore
- rocks.kfs.CyberSource/Configuration.cs
- rocks.kfs.CyberSource/Controls/CyberSourceHostedPaymentControl.cs
- rocks.kfs.CyberSource/rocks.kfs.CyberSource.csproj
- rocks.kfs.JavaScript.Obsidian/.eslintrc.js
- rocks.kfs.JavaScript.Obsidian/.gitignore
- …
=> Cybersource Gateway Updates

.gitignore, KFSRock.sln.kfs, README.md, ZZZ_Archive/rocks.kfs.Edify/Communications/Transport/EdifyHTTP.cs, rocks.kfs.CyberSource/Configuration.cs, rocks.kfs.CyberSource/Controls/CyberSourceHostedPaymentControl.cs, rocks.kfs.CyberSource/Gateway.cs, rocks.kfs.CyberSource/Model/AddressToken.cs, rocks.kfs.CyberSource/Properties/AssemblyInfo.cs, rocks.kfs.CyberSource/rocks.kfs.CyberSource.csproj, rocks.kfs.JavaScript.Obsidian/.eslintrc.js, rocks.kfs.JavaScript.Obsidian/.gitignore, rocks.kfs.JavaScript.Obsidian/.vscode/launch.json, rocks.kfs.JavaScript.Obsidian/PROJECT_MIGRATION_LOG.txt, rocks.kfs.JavaScript.Obsidian/build/.eslintrc.js, rocks.kfs.JavaScript.Obsidian/build/build-fast.js, rocks.kfs.JavaScript.Obsidian/build/build-types.js, rocks.kfs.JavaScript.Obsidian/jest.config.js, rocks.kfs.JavaScript.Obsidian/nuget.config, rocks.kfs.JavaScript.Obsidian/package-lock.json, rocks.kfs.JavaScript.Obsidian/package.json, rocks.kfs.JavaScript.Obsidian/rocks.kfs.JavaScript.Obsidian.esproj, rocks.kfs.JavaScript.Obsidian/rocks.kfs.JavaScript.Obsidian.njsproj, rocks.kfs.JavaScript.Obsidian/rollup.config.js, rocks.kfs.JavaScript.Obsidian/src/Controls/cyberSourceGatewayControl.obs, rocks.kfs.JavaScript.Obsidian/tests/tsconfig.json, rocks.kfs.JavaScript.Obsidian/tsconfig.json
Duplicate of https://github.com/KingdomFirst/RockAssemblies/pull/157/files with v16 specific changes. Commit history is a bit odd though...
=> Cybersource Updates hotfix-16

rocks.kfs.StepsToCare/Migrations/023_UpdateAttributes.cs, rocks.kfs.StepsToCare/Properties/AssemblyInfo.cs
Steps to Care Migration Fix
---------
Steps to Care Migration Fix
---------
Warranty
---------
No
---------
rocks.kfs.StepsToCare/Migrations/023_UpdateAttributes.cs
---------
No
=> Steps to Care Migration Fix

KFSRock.sln.kfs, rocks.kfs.CampusEngagementEmailSend/Jobs/CampusEngagementEmailSend.cs, rocks.kfs.CustomGroupCommunication/Jobs/MeetingGroupReminder.cs, rocks.kfs.FundraisingParticipantSummary/Jobs/FundraisingParticipantSummary.cs, rocks.kfs.GroupRoleAttendanceReminder/Jobs/GroupRoleSendAttendanceReminders.cs, rocks.kfs.GroupRoleAttendanceReminder/rocks.kfs.GroupRoleAttendanceReminder.csproj, rocks.kfs.InactivateGroups/Jobs/InactivateGroups.cs, rocks.kfs.Microsoft365Utilities/Jobs/LaunchWorkflowFromEWSAccount.cs, rocks.kfs.PersonAudience/Jobs/SetPersonAudience.cs, rocks.kfs.RoundRobinGroupAssignment/Jobs/RoundRobinGroupAssignment.cs, rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupEmail.cs, rocks.kfs.ScheduledGroupCommunication/Jobs/SendScheduledGroupSMS.cs, rocks.kfs.ScheduledGroupCommunication/Migrations/001_AddSystemData.cs, rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs, rocks.kfs.StepsToCare/Migrations/019_AddFieldTypeAndAttributeMatrix.cs, rocks.kfs.Zoom/Jobs/ZoomMeetingGroupReminder.cs, rocks.kfs.Zoom/Jobs/ZoomRoomSchedulingAndMaintenance.cs
Updated Context changes that no longer carry collections of data and Deprecated IJob to RockJob changes. Also, some other recommended changes.
---------
- Fixed a potential data issue in future versions of Rock.
---------
Warranty
---------
No
---------
- rocks.kfs.CampusEngagementEmailSend/Jobs/CampusEngagementEmailSend.cs
- rocks.kfs.GroupRoleAttendanceReminder/Jobs/GroupRoleSendAttendanceReminders.cs
- rocks.kfs.GroupRoleAttendanceReminder/rocks.kfs.GroupRoleAttendanceReminder.csproj
- rocks.kfs.PersonAudience/Jobs/SetPersonAudience.cs
- rocks.kfs.ScheduledGroupCommunication/Migrations/001_AddSystemData.cs
- rocks.kfs.StepsToCare/Jobs/CareNeedAutomatedProcesses.cs
- rocks.kfs.StepsToCare/Migrations/019_AddFieldTypeAndAttributeMatrix.cs
---------
No
=> Context and RockJob Changes for future Version Support

rocks.kfs.EventBrite/Eventbrite.cs
Move fix into SyncAttendee due to webhook skipping previous section it was added to in #168. Also webhook needs update due to this bug, located in https://github.com/KingdomFirst/RockBlocks/pull/190.
=> Eventbrite fix

KFSRock.sln.kfs
Update KFS Sln for 16.6
---------
Update KFS Sln for 16.6
---------
Warranty
---------
No
---------
KFSRock.sln.kfs
---------
No
=> Update KFS Sln for 16.6

KFSRock.sln.kfs
Update KFS SLN to 16.9
---------
Update KFS SLN to 16.9
---------
Warranty
---------
No
---------
KFSRock.sln.kfs
---------
Requires 16.9
=> Update KFS SLN to 16.9
